# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpocore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'ordering': ('_order',), 'verbose_name': 'Carousel item', 'verbose_name_plural': 'Carousel items'},
        ),
        migrations.AlterModelOptions(
            name='formalstatement',
            options={'verbose_name': 'Formal statement', 'verbose_name_plural': 'Formal statements'},
        ),
        migrations.AlterModelOptions(
            name='homepagepage',
            options={'ordering': ('_order',), 'verbose_name': 'Homepage page', 'verbose_name_plural': 'Homepage pages'},
        ),
        migrations.AlterModelOptions(
            name='informalstatement',
            options={'verbose_name': 'Informal statement', 'verbose_name_plural': 'Informal statements'},
        ),
        migrations.AlterModelOptions(
            name='notablesupporter',
            options={'ordering': ('_order',), 'verbose_name': 'Notable supporter', 'verbose_name_plural': 'Notable supporters'},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ('_order',), 'verbose_name': 'Phase', 'verbose_name_plural': 'Phases'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='statementpage',
            options={'ordering': ('_order',), 'verbose_name': 'Statement page', 'verbose_name_plural': 'Statement pages'},
        ),
        migrations.AlterModelOptions(
            name='supporter',
            options={'verbose_name': 'Supporter', 'verbose_name_plural': 'Supporters'},
        ),
        migrations.AlterModelOptions(
            name='supporterpage',
            options={'ordering': ('_order',), 'verbose_name': 'Supporter page', 'verbose_name_plural': 'Supporter pages'},
        ),
        migrations.AlterModelOptions(
            name='supportgroup',
            options={'verbose_name': 'Support group', 'verbose_name_plural': 'Support groups'},
        ),
        migrations.AlterField(
            model_name='formalstatement',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='informalstatement',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='Organization'),
        ),
    ]
