# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 10:24
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rpocore', '0002_auto_20160901_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepage',
            name='supporter_statistics',
            field=mezzanine.core.fields.RichTextField(blank=True, help_text='Please enter the markup for this block.', verbose_name='Become supporter block'),
        ),
    ]
