# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpocore', '0003_auto_20160916_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
