# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpocore', '0004_auto_20160920_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notablesupporter',
            options={'ordering': ('_order',), 'verbose_name': 'First signatory', 'verbose_name_plural': 'First signatories'},
        ),
    ]
