# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rpocore', '0006_auto_20160921_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo of organization')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Supporting organizations',
                'ordering': ('_order',),
                'verbose_name': 'Supporting organization',
            },
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='rpocore.HomepagePage', verbose_name='Homepage'),
        ),
        migrations.AlterField(
            model_name='homepagepage',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpocore.Process', verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='notablesupporter',
            name='supporter_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notable_supporters', to='rpocore.SupporterPage', verbose_name='Supporter page'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpocore.Process', verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='statementpage',
            name='formal_statements',
            field=models.ManyToManyField(blank=True, to='rpocore.FormalStatement', verbose_name='Formal statements'),
        ),
        migrations.AlterField(
            model_name='statementpage',
            name='informal_statements',
            field=models.ManyToManyField(blank=True, to='rpocore.InformalStatement', verbose_name='Informal statements'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='support_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rpocore.SupportGroup', verbose_name='Support group'),
        ),
    ]
