# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rpocore', '0007_auto_20160927_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('datetime', models.DateTimeField(verbose_name='Date and time')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'verbose_name': 'Event',
                'ordering': ('_order',),
            },
        ),
    ]
